project: 124M-CORRECT-OPT-SCION-budget1336934400
run: optimistic-scion-demo_32_40800_0.95_0.95_0.0005
input_bin: data/fineweb100B/fineweb_train_*.bin
input_val_bin: data/fineweb100B/fineweb_val_*.bin
batch_size: 32
device_batch_size: 32
sequence_length: 1024
sequence_length_eval: 1024
num_iterations: 40800
warmup_iters: 0
warmdown_iters: 11424
val_loss_every: 100
val_tokens: 10485760
save_every: 0
n_layer: 12
n_head: 6
n_embd: 768
lr_embed: 0.0005
lr_matrix: 0.0005
scale_embed: 25
scale_matrix: 3000
d_mom1: 0.95
d_mom2: 0.95
seed: 101
adj_embed: 0.5
adj_matrix: 1
