project: 124M-CORRECT-OPT-SCION-budget1336934400
run: optimistic-scion-demo_128_10200_0.95_0.95_5e-05
input_bin: data/fineweb100B/fineweb_train_*.bin
input_val_bin: data/fineweb100B/fineweb_val_*.bin
batch_size: 128
device_batch_size: 32
sequence_length: 1024
sequence_length_eval: 1024
num_iterations: 10200
warmup_iters: 0
warmdown_iters: 2856
val_loss_every: 100
val_tokens: 10485760
save_every: 0
n_layer: 12
n_head: 6
n_embd: 768
lr_embed: 5.0e-05
lr_matrix: 5.0e-05
scale_embed: 100
scale_matrix: 3000
d_mom1: 0.95
d_mom2: 0.95
seed: 101
adj_embed: 2
adj_matrix: 1
