project: experimentLR-check-budget-5520925000
run: scion-demo_380_9850_6e-05
input_bin: data/fineweb10B/fineweb_train_*.bin
input_val_bin: data/fineweb10B/fineweb_val_*.bin
batch_size: 380
device_batch_size: 5
sequence_length: 1475
num_iterations: 9850
warmup_iters: 0
warmdown_iters: 2758
val_loss_every: 1000
val_tokens: 10649500
save_every: 0
n_layer: 24
n_head: 10
n_embd: 1280
unconstrained: false
momentum: 0.1
weight_decay: 0.0
lr_embed: 6.0e-05
lr_matrix: 6.0e-05
scale_embed: 50
scale_matrix: 3000
seed: 101
