project: experimentLR-check-budget-5520150000
run: scion-demo_360_10575_0.00024
input_bin: data/fineweb10B/fineweb_train_*.bin
input_val_bin: data/fineweb10B/fineweb_val_*.bin
batch_size: 360
device_batch_size: 5
sequence_length: 1450
num_iterations: 10575
warmup_iters: 0
warmdown_iters: 2961
val_loss_every: 1000
val_tokens: 10440000
save_every: 0
n_layer: 24
n_head: 10
n_embd: 1280
unconstrained: false
momentum: 0.1
weight_decay: 0.0
lr_embed: 0.00024
lr_matrix: 0.00024
scale_embed: 50
scale_matrix: 3000
seed: 101
