project: experimentlarge-model-budget8357580000
run: scion-demo_420_12060_0.000103
input_bin: data/fineweb10B/fineweb_train_*.bin
input_val_bin: data/fineweb10B/fineweb_val_*.bin
batch_size: 420
device_batch_size: 5
sequence_length: 1650
num_iterations: 12060
warmup_iters: 0
warmdown_iters: 3376
val_loss_every: 1000
val_tokens: 11088000
save_every: 0
n_layer: 36
n_head: 20
n_embd: 1280
unconstrained: false
momentum: 0.1
weight_decay: 0.0
lr_embed: 0.000103
lr_matrix: 0.000103
scale_embed: 50
scale_matrix: 3000
seed: 101
