project: experimentcheckLR-large-model-budget16172236800
run: scion-demo_600_13161_0.00018720000000000002
input_bin: data/fineweb10B/fineweb_train_*.bin
input_val_bin: data/fineweb10B/fineweb_val_*.bin
batch_size: 600
device_batch_size: 2
sequence_length: 2048
sequence_length_eval: 1024
num_iterations: 13161
warmup_iters: 0
warmdown_iters: 3685
val_loss_every: 1000
val_tokens: 10485760
save_every: 0
n_layer: 48
n_head: 25
n_embd: 1600
unconstrained: false
momentum: 0.1
weight_decay: 0.0
lr_embed: 0.00018720000000000002
lr_matrix: 0.00018720000000000002
scale_embed: 50
scale_matrix: 3000
seed: 101
