project: experimentlarge-model-budget8356608000
run: scion-demo_512_12090_2.4599999999999998e-05
input_bin: data/fineweb10B/fineweb_train_*.bin
input_val_bin: data/fineweb10B/fineweb_val_*.bin
batch_size: 512
device_batch_size: 4
sequence_length: 1350
num_iterations: 12090
warmup_iters: 0
warmdown_iters: 3385
val_loss_every: 1000
val_tokens: 10476000
save_every: 0
n_layer: 36
n_head: 20
n_embd: 1280
unconstrained: false
momentum: 0.1
weight_decay: 0.0
lr_embed: 2.4599999999999998e-05
lr_matrix: 2.4599999999999998e-05
scale_embed: 50
scale_matrix: 3000
seed: 101
